services:
  varnish:
    image: varnish:7.5
    volumes:
      - ./var/varnish/default.vcl:/etc/varnish/default.vcl
    ports:
      - ${VARNISH_PORT:-80}:80
    tmpfs:
      - /var/lib/varnish/varnishd:exec
    environment:
      - VARNISH_SIZE=2G
    command: -p default_keep=300
    depends_on:
      - web
