services:
  web:
    user: magento
    image: magento-host:1.0.0
    build:
      context: .
      args:
        - PHP_VERSION=${PHP_VERSION:-8.1}
    environment:
      - PHP_VERSION=${PHP_VERSION:-8.1}
    ports:
      - 80:80
      - 8000:8000
      - 35729:35729
    volumes:
      - ./magento-app:/magento-app
      - web-user-cache:/home/magento/.cache
      - web-user-config:/home/magento/.config
      - web-user-local:/home/magento/.local
      - web-user-ssh:/home/magento/.ssh
      - web-user-vscode-server:/home/magento/.vscode-server
      - web-magetools-vars:/home/magento/.magetools/var
      - web-sites-available:/etc/nginx/sites-available
      - web-sites-enabled:/etc/nginx/sites-enabled
    depends_on:
      - db
      - search-engine

  db:
    image: mysql:8.0
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --innodb-buffer-pool-size=1G
      - --log-bin-trust-function-creators=ON
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - db-volume:/var/lib/mysql

  search-engine:
    image: opensearchproject/opensearch:2.12.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=magentoDockerOpenSearch123!
    ports:
      - 9200:9200
volumes:
  db-volume:
  web-user-cache:
  web-user-config:
  web-user-local:
  web-user-ssh:
  web-user-vscode-server:
  web-magetools-vars:
  web-sites-available:
  web-sites-enabled:
