services:
  web:
    user: magento
    image: magento-host:1.0.0
    build: ./
    ports:
      - ${MAGE_PORT:-80}:80
      - ${GRUNT_PORT:-8000}:8000
    volumes:
      - ./magento-app:/magento-app
      - web-user-cache:/home/magento/.cache
      - web-user-config:/home/magento/.config
      - web-user-local:/home/magento/.local
      - web-user-ssh:/home/magento/.ssh
      - web-user-vscode-server:/home/magento/.vscode-server
    depends_on:
      - db
      - search-engine

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - ${MYSQL_PORT:-3306}:3306
    volumes:
      - db-volume:/var/lib/mysql

  search-engine:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    environment:
      - discovery.type=single-node
volumes:
  db-volume:
  web-user-cache:
  web-user-config:
  web-user-local:
  web-user-ssh:
  web-user-vscode-server:
